-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.documents (
    document_id serial NOT NULL,
    json_data jsonb,
    document_type text NOT NULL,  
    citizen_id integer NOT NULL,
    PRIMARY KEY (document_id)
);


CREATE TABLE IF NOT EXISTS public.document_scans
(
    scan_id serial NOT NULL,
    page_number integer NOT NULL,
    scan_file bytea,
    document_id integer NOT NULL,
    PRIMARY KEY (scan_id)
);

CREATE TABLE IF NOT EXISTS public.citizens
(
    citizen_id serial NOT NULL, -- дополнительные поля, если требуется
    PRIMARY KEY (citizen_id)
);

CREATE TABLE IF NOT EXISTS public.importance_weights
(
    weight_id serial NOT NULL,
    weights jsonb,
    document_id integer NOT NULL,
    PRIMARY KEY (weight_id)
);

CREATE TABLE IF NOT EXISTS public.osint_results
(
    result_id serial NOT NULL,
    findings jsonb,
    citizen_id integer NOT NULL,
    PRIMARY KEY (result_id)
);

ALTER TABLE IF EXISTS public.documents
    ADD FOREIGN KEY (citizen_id)
    REFERENCES public.citizens (citizen_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.document_scans
    ADD FOREIGN KEY (document_id)
    REFERENCES public.documents (document_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.importance_weights
    ADD FOREIGN KEY (document_id)
    REFERENCES public.documents (document_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.osint_results
    ADD FOREIGN KEY (citizen_id)
    REFERENCES public.citizens (citizen_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;

END;